# Generated by Django 6.0.5 on 2026-05-19 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_wastereport_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='ignored_by',
            field=models.ManyToManyField(blank=True, related_name='ignored_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
